# ------------------------------------------------------------
# Theme: Pure-Latin v2.0 - Alacritty Config
# ------------------------------------------------------------

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#262A33' # Primary BG
foreground = '#D3DEE9' # Primary Text

[colors.cursor]
text = '#262A33'
cursor = '#5E81AC' # Primary Accent

# Palette (Usando colores de tu tema)
[colors.normal]
black = '#1E222A' # Base
red = '#BF616A'   # Error
green = '#A3BE8C' # Success
yellow = '#EBCB8B' # Warning
blue = '#5E81AC'
magenta = '#8A7A8A'
cyan = '#88C0D0'
white = '#D3DEE9'

[colors.bright]
black = '#333842'
red = '#BF616A'
green = '#A3BE8C'
yellow = '#EBCB8B'
blue = '#81A1C1'
magenta = '#8A7A8A'
cyan = '#88C0D0'
white = '#D3DEE9'
